baseURL: "https://bumpxfeed.com/"
languageCode: en-us
title: bumpXfeed
paginate: 5
theme: ["PaperMod"]

# https://gohugo.io/getting-started/configuration/#enablegitinfo
enableGitInfo: true

# https://gohugo.io/getting-started/configuration/#configure-front-matter
frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: G-JVJ5ZYFD7R

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: bumpXfeed
  description: "Pro wrestling and sports entertainment destination with content about WWE, AEW, NJPW, ROH, Impact!, and more."
  keywords: [Pro Wrestling School, Pro Wrestling Training, Pro Wrestling, WWE, AEW, NJPW, ROH, Impact!]
  author: Jalen Wu
  # author: ["Me", "You"] # multiple authors
  images: ["images/bf-black.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  gtm_id: GTM-WPGJ28D
  gtm_datalayer: basic
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "https://bumpxfeed.com/images/bfblack32.png"
    favicon16x16: "https://bumpxfeed.com/images/bfblack16.png"
    favicon32x32: "https://bumpxfeed.com/images/bfblack32.png"
    apple_touch_icon: "https://bumpxfeed.com/images/bfblack180.png"
    safari_pinned_tab: "https://bumpxfeed.com/images/bfblack32.png"

  label:
    text: bumpXfeed
    icon: "images/bfblack180.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: bumpXfeed
    subtitle: "Pro wrestling and sports entertainment destination with content about WWE, AEW, NJPW, ROH, Impact!, and more."
    imageUrl: "images/bf-black.png"
    imageWidth: 240
    imageHeight: 240
    imageTitle: bumpXfeed
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/bumpxfeed"
    - name: tiktok
      url: "https://tiktok.com/@bumpxfeed"
    - name: youtube 
      url: "https://youtube.com/@bumpxfeed"  
    - name: facebook
      url: "https://facebook.com/@bumpxfeed"
    - name: github
      url: "https://github.com/jhach/bump-paper"

  # analytics:
    #google:
      # SiteVerificationTag: "XYZabc"
    # bing:
      # SiteVerificationTag: "XYZabc"
    # yandex:
      # SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # editPost:
    # URL: "https://github.com/jhach/bump-paper/content"
    # Text: "Suggest Changes" # edit text
    # appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  # fuseOpts:
    # isCaseSensitive: false
    # shouldSort: true
    # location: 0
    # distance: 1000
    # threshold: 0.4
    # minMatchCharLength: 0
    # keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: about
      name: about
      url: /about/
      weight: 40
    # - identifier: Jalen Wu
      # name: Jalen Wu
      # url: https://youtube.com/@jalenwu
      # weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: false
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
